<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "activities".
 *
 * @property integer $activity_id
 * @property string $activity_name
 * @property string $description
 * @property string $location
 * @property string $activity_date
 * @property string $start_time
 * @property string $end_time
 *
 * @property \common\models\TourActivities[] $tourActivities
 * @property \common\models\Tour[] $tours
 */
abstract class Activities extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'activities';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['description', 'location', 'activity_date'], 'default', 'value' => null],
            [['activity_name'], 'required'],
            [['description'], 'string'],
            [['activity_date','start_time','end_time'], 'safe'],
            [['activity_name', 'location'], 'string', 'max' => 100]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'activity_id' => Yii::t('app', 'Activity ID'),
            'activity_name' => Yii::t('app', 'Activity Name'),
            'description' => Yii::t('app', 'Description'),
            'location' => Yii::t('app', 'Location'),
            'activity_date' => Yii::t('app', 'Activity Date'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTourActivities()
    {
        return $this->hasMany(\common\models\TourActivities::class, ['activity_id' => 'activity_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTours()
    {
        return $this->hasMany(\common\models\Tour::class, ['tour_id' => 'tour_id'])->viaTable('tour_activities', ['activity_id' => 'activity_id']);
    }

}
