<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "booking_payments".
 *
 * @property integer $payment_id
 * @property integer $booking_id
 * @property string $amount
 * @property string $payment_method
 * @property string $payment_date
 * @property string $transaction_reference
 * @property string $notes
 * @property string $created_at
 *
 * @property \common\models\ServiceBookings $booking
 */
abstract class BookingPayments extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'booking_payments';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        // $behaviors['timestamp'] = [
        //     'class' => TimestampBehavior::class,
        //                             'updatedAtAttribute' => false,
        // ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['transaction_reference', 'notes'], 'default', 'value' => null],
            [['booking_id', 'amount', 'payment_method'], 'required'],
            [['booking_id'], 'integer'],
            [['amount'], 'number'],
            [['payment_date'], 'safe'],
            [['notes'], 'string'],
            [['payment_method'], 'string', 'max' => 50],
            [['transaction_reference'], 'string', 'max' => 100],
            [['booking_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\ServiceBookings::class, 'targetAttribute' => ['booking_id' => 'booking_id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'payment_id' => Yii::t('app', 'Payment ID'),
            'booking_id' => Yii::t('app', 'Booking ID'),
            'amount' => Yii::t('app', 'Amount'),
            'payment_method' => Yii::t('app', 'Payment Method'),
            'payment_date' => Yii::t('app', 'Payment Date'),
            'transaction_reference' => Yii::t('app', 'Transaction Reference'),
            'notes' => Yii::t('app', 'Notes'),
            'created_at' => Yii::t('app', 'Created At'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBooking()
    {
        return $this->hasOne(\common\models\ServiceBookings::class, ['booking_id' => 'booking_id']);
    }

}
