<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "booking_history".
 *
 * @property integer $history_id
 * @property integer $booking_id
 * @property string $old_status
 * @property string $new_status
 * @property string $changed_at
 * @property string $changed_by
 */
abstract class BookingHistory extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'booking_history';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['old_status', 'new_status', 'changed_by'], 'default', 'value' => null],
            [['booking_id'], 'required'],
            [['booking_id'], 'integer'],
            [['changed_at'], 'safe'],
            [['old_status', 'new_status'], 'string', 'max' => 20],
            [['changed_by'], 'string', 'max' => 50]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'history_id' => Yii::t('app', 'History ID'),
            'booking_id' => Yii::t('app', 'Booking ID'),
            'old_status' => Yii::t('app', 'Old Status'),
            'new_status' => Yii::t('app', 'New Status'),
            'changed_at' => Yii::t('app', 'Changed At'),
            'changed_by' => Yii::t('app', 'Changed By'),
        ]);
    }

}
