<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "contact_info".
 *
 * @property integer $contact_id
 * @property string $platform
 * @property string $contact_value
 * @property string $contact_type
 * @property integer $is_active
 */
abstract class Contact extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'contact_info';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['contact_type'], 'default', 'value' => null],
            [['is_active'], 'default', 'value' => 1],
            [['platform', 'contact_value'], 'required'],
            [['is_active'], 'integer'],
            [['platform'], 'string', 'max' => 50],
            [['contact_value'], 'string', 'max' => 100],
            [['contact_type'], 'string', 'max' => 20]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'contact_id' => Yii::t('app', 'Contact ID'),
            'platform' => Yii::t('app', 'Platform'),
            'contact_value' => Yii::t('app', 'Contact Value'),
            'contact_type' => Yii::t('app', 'Contact Type'),
            'is_active' => Yii::t('app', 'Is Active'),
        ]);
    }

}
