<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "website_images".
 *
 * @property integer $id
 * @property string $path
 * @property string $page
 * @property string $section
 * @property string $alt_text
 * @property string $caption
 * @property integer $is_active
 * @property string $created_at
 * @property string $updated_at
 */
abstract class Images extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'website_images';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['caption'], 'default', 'value' => null],
            [['is_active'], 'default', 'value' => 1],
            [['path', 'page', 'section', 'alt_text'], 'required'],
            [['caption'], 'string'],
            [['is_active'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['path', 'alt_text'], 'string', 'max' => 255],
            [['page'], 'string', 'max' => 20],
            [['section'], 'string', 'max' => 50]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => Yii::t('app', 'ID'),
            'path' => Yii::t('app', 'Path'),
            'page' => Yii::t('app', 'Page'),
            'section' => Yii::t('app', 'Section'),
            'alt_text' => Yii::t('app', 'Alt Text'),
            'caption' => Yii::t('app', 'Caption'),
            'is_active' => Yii::t('app', 'Is Active'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ]);
    }

}
