<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "lkp_service_types".
 *
 * @property integer $service_type_id
 * @property string $type_name
 * @property string $description
 * @property integer $is_active
 *
 * @property \common\models\Services[] $services
 */
abstract class LkpServiceTypes extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'lkp_service_types';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['description'], 'default', 'value' => null],
            [['is_active'], 'default', 'value' => 1],
            [['type_name'], 'required'],
            [['description'], 'string'],
            [['is_active'], 'integer'],
            [['type_name'], 'string', 'max' => 50],
            [['type_name'], 'unique']
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'service_type_id' => Yii::t('app', 'Service Type ID'),
            'type_name' => Yii::t('app', 'Type Name'),
            'description' => Yii::t('app', 'Description'),
            'is_active' => Yii::t('app', 'Is Active'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServices()
    {
        return $this->hasMany(\common\models\Services::class, ['service_type_id' => 'service_type_id']);
    }

}
