<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "locations".
 *
 * @property integer $location_id
 * @property string $name
 * @property string $description
 * @property string $latitude
 * @property string $longitude
 * @property integer $is_active
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \common\models\ServiceLocations[] $serviceLocations
 */
abstract class Locations extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'locations';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        // $behaviors['timestamp'] = [
        //     'class' => TimestampBehavior::class,
        //                 ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['description', 'latitude', 'longitude'], 'default', 'value' => null],
            [['is_active'], 'default', 'value' => 1],
            [['name'], 'required'],
            [['description'], 'string'],
            [['latitude', 'longitude'], 'number'],
            [['is_active'], 'integer'],
            [['name'], 'string', 'max' => 100]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'location_id' => Yii::t('app', 'Location ID'),
            'name' => Yii::t('app', 'Name'),
            'description' => Yii::t('app', 'Description'),
            'latitude' => Yii::t('app', 'Latitude'),
            'longitude' => Yii::t('app', 'Longitude'),
            'is_active' => Yii::t('app', 'Is Active'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServiceLocations()
    {
        return $this->hasMany(\common\models\ServiceLocations::class, ['location_id' => 'location_id']);
    }

}
