<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "package_inclusions".
 *
 * @property integer $inclusion_id
 * @property integer $tour_id
 * @property string $inclusion_name
 * @property string $description
 *
 * @property \common\models\Tour $tour
 */
abstract class Package extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'package_inclusions';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['tour_id', 'inclusion_name'], 'required'],
            [['tour_id'], 'integer'],
            [['inclusion_name'], 'string', 'max' => 100],
            [['description'], 'string', 'max' => 100],
            [['tour_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Tour::class, 'targetAttribute' => ['tour_id' => 'tour_id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'inclusion_id' => Yii::t('app', 'Inclusion ID'),
            'tour_id' => Yii::t('app', 'Tour ID'),
            'inclusion_name' => Yii::t('app', 'Inclusion Name'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTour()
    {
        return $this->hasOne(\common\models\Tour::class, ['tour_id' => 'tour_id']);
    }

}
