<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "tour_reviews".
 *
 * @property integer $review_id
 * @property integer $tour_id
 * @property integer $customer_id
 * @property integer $rating
 * @property string $comment
 * @property string $review_date
 *
 * @property \common\models\Customer $customer
 * @property \common\models\Tour $tour
 */
abstract class Reviews extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tour_reviews';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['comment'], 'default', 'value' => null],
            [['rating'], 'default', 'value' => 5],
            [['tour_id', 'customer_id'], 'required'],
            [['tour_id', 'customer_id', 'rating'], 'integer'],
            [['comment'], 'string'],
            [['review_date'], 'safe'],
            [['tour_id', 'customer_id'], 'unique', 'targetAttribute' => ['tour_id', 'customer_id']],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Customer::class, 'targetAttribute' => ['customer_id' => 'customer_id']],
            [['tour_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Tour::class, 'targetAttribute' => ['tour_id' => 'tour_id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'review_id' => Yii::t('app', 'Review ID'),
            'tour_id' => Yii::t('app', 'Tour ID'),
            'customer_id' => Yii::t('app', 'Customer ID'),
            'rating' => Yii::t('app', 'Rating'),
            'comment' => Yii::t('app', 'Comment'),
            'review_date' => Yii::t('app', 'Review Date'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(\common\models\Customer::class, ['customer_id' => 'customer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTour()
    {
        return $this->hasOne(\common\models\Tour::class, ['tour_id' => 'tour_id']);
    }

}
