<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "service_inclusions".
 *
 * @property integer $inclusion_id
 * @property integer $service_id
 * @property string $name
 * @property string $description
 * @property integer $display_order
 * 
 * @property \common\models\Services $service
 */
abstract class ServiceInclusions extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'service_inclusions';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['description'], 'default', 'value' => null],
            [['display_order'], 'default', 'value' => 0],
            [['service_id', 'name'], 'required'],
            [['service_id', 'display_order'], 'integer'],
            [['description'], 'string'],
            [['name'], 'string', 'max' => 100],
            [['service_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Services::class, 'targetAttribute' => ['service_id' => 'service_id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'inclusion_id' => Yii::t('app', 'Inclusion ID'),
            'service_id' => Yii::t('app', 'Service ID'),
            'name' => Yii::t('app', 'Name'),
            'description' => Yii::t('app', 'Description'),
            'display_order' => Yii::t('app', 'Display Order'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getService()
    {
        return $this->hasOne(\common\models\Services::class, ['service_id' => 'service_id']);
    }

}
