<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "service_images".
 *
 * @property integer $image_id
 * @property integer $service_id
 * @property string $image_url
 * @property string $alt_text
 * @property string $description
 * @property integer $is_featured
 * @property integer $display_order
 * @property string $created_at
 *
 * @property \common\models\Services $service
 */
abstract class ServiceImages extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'service_images';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        // $behaviors['timestamp'] = [
        //     'class' => TimestampBehavior::class,
        //                             'updatedAtAttribute' => false,
        // ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['alt_text', 'description'], 'default', 'value' => null],
            [['display_order'], 'default', 'value' => 0],
            [['service_id', 'image_url'], 'required'],
            [['service_id', 'is_featured', 'display_order'], 'integer'],
            [['description'], 'string'],
            [['image_url'], 'string', 'max' => 255],
            [['alt_text'], 'string', 'max' => 100],
            [['service_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Services::class, 'targetAttribute' => ['service_id' => 'service_id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'image_id' => Yii::t('app', 'Image ID'),
            'service_id' => Yii::t('app', 'Service ID'),
            'image_url' => Yii::t('app', 'Image Url'),
            'alt_text' => Yii::t('app', 'Alt Text'),
            'description' => Yii::t('app', 'Description'),
            'is_featured' => Yii::t('app', 'Is Featured'),
            'display_order' => Yii::t('app', 'Display Order'),
            'created_at' => Yii::t('app', 'Created At'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getService()
    {
        return $this->hasOne(\common\models\Services::class, ['service_id' => 'service_id']);
    }

}
