<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "service_pricing".
 * 
 * @property integer $pricing_id
 * @property integer $service_id
 * @property string $start_date
 * @property string $end_date
 * @property string $base_price
 * @property string $price_per_couple
 * @property integer $season_id
 *
 * @property \common\models\LkpSeasons $season
 * @property \common\models\Services $service
 */
abstract class ServicePricing extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'service_pricing';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['season_id'], 'default', 'value' => null],
            [['service_id', 'start_date', 'end_date', 'base_price', 'price_per_couple'], 'required'],
            [['service_id', 'season_id'], 'integer'],
            [['start_date', 'end_date'], 'safe'],
            [['base_price', 'price_per_couple'], 'number'],
            [['service_id', 'start_date', 'end_date'], 'unique', 'targetAttribute' => ['service_id', 'start_date', 'end_date']],
            [['season_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\LkpSeasons::class, 'targetAttribute' => ['season_id' => 'season_id']],
            [['service_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Services::class, 'targetAttribute' => ['service_id' => 'service_id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'pricing_id' => Yii::t('app', 'Pricing ID'),
            'service_id' => Yii::t('app', 'Service ID'),
            'start_date' => Yii::t('app', 'Start Date'),
            'end_date' => Yii::t('app', 'End Date'),
            'base_price' => Yii::t('app', 'Base Price'),
            'price_per_couple' => Yii::t('app', 'Price Per Couple'),
            'season_id' => Yii::t('app', 'Season'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSeason()
    {
        return $this->hasOne(\common\models\LkpSeasons::class, ['season_id' => 'season_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getService()
    {
        return $this->hasOne(\common\models\Services::class, ['service_id' => 'service_id']);
    }

}
