<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "service_to_category".
 *
 * @property integer $service_id
 * @property integer $category_id
 *
 * @property \common\models\ServiceCategories $category
 * @property \common\models\Services $service
 */
abstract class ServiceToCategory extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'service_to_category';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['service_id', 'category_id'], 'required'],
            [['service_id', 'category_id'], 'integer'],
            [['service_id', 'category_id'], 'unique', 'targetAttribute' => ['service_id', 'category_id']],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\ServiceCategories::class, 'targetAttribute' => ['category_id' => 'category_id']],
            [['service_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Services::class, 'targetAttribute' => ['service_id' => 'service_id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'service_id' => Yii::t('app', 'Service ID'),
            'category_id' => Yii::t('app', 'Category ID'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(\common\models\ServiceCategories::class, ['category_id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getService()
    {
        return $this->hasOne(\common\models\Services::class, ['service_id' => 'service_id']);
    }

}
