<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "tour_activities".
 *
 * @property integer $tour_id
 * @property integer $activity_id
 *
 * @property \common\models\Activities $activity
 * @property \common\models\Tour $tour
 */
abstract class TourActivities extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tour_activities';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['tour_id', 'activity_id'], 'required'],
            [['tour_id', 'activity_id'], 'integer'],
            [['tour_id', 'activity_id'], 'unique', 'targetAttribute' => ['tour_id', 'activity_id']],
            [['activity_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Activities::class, 'targetAttribute' => ['activity_id' => 'activity_id']],
            [['tour_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Tour::class, 'targetAttribute' => ['tour_id' => 'tour_id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'tour_id' => Yii::t('app', 'Tour ID'),
            'activity_id' => Yii::t('app', 'Activity ID'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActivity()
    {
        return $this->hasOne(\common\models\Activities::class, ['activity_id' => 'activity_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTour()
    {
        return $this->hasOne(\common\models\Tour::class, ['tour_id' => 'tour_id']);
    }

}
