<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "tours".
 *
 * @property integer $tour_id
 * @property string $tour_name
 * @property string $description
 * @property string $start_date
 * @property string $end_date
 * @property string $booking_deadline
 * @property integer $duration_days
 * @property integer $duration_nights
 * @property string $starting_point
 * @property string $destination
 * @property string $single_price
 * @property string $couple_price
 * @property integer $total_seats
 * @property integer $available_seats
 * @property string $status
 * @property integer $is_deleted
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \common\models\Activities[] $activities
 * @property \common\models\Bookings[] $bookings
 * @property \common\models\Customers[] $customers
 * @property \common\models\Events[] $events
 * @property \common\models\TourGuides[] $guides
 * @property \common\models\PackageInclusions[] $packageInclusions
 * @property \common\models\TourActivities[] $tourActivities
 * @property \common\models\TourGuides[] $tourGuides
 * @property \common\models\TourGuidesAssignments[] $tourGuidesAssignments
 * @property \common\models\TourImages[] $tourImages
 * @property \common\models\TourReviews[] $tourReviews
 */
abstract class Tours extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tours';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['description', 'destination'], 'default', 'value' => null],
            [['status'], 'default', 'value' => 'active'],
            [['is_deleted'], 'default', 'value' => 0],
            [['tour_name', 'start_date', 'end_date', 'booking_deadline', 'duration_days', 'duration_nights', 'starting_point', 'single_price', 'couple_price', 'total_seats', 'available_seats'], 'required'],
            [['description'], 'string'],
            [['start_date', 'end_date', 'booking_deadline'], 'safe'],
            [['duration_days', 'duration_nights', 'total_seats', 'available_seats', 'is_deleted'], 'integer'],
            [['single_price', 'couple_price'], 'number'],
            [['tour_name', 'starting_point'], 'string', 'max' => 100],
            [['destination'], 'string', 'max' => 255],
            [['status'], 'string', 'max' => 10]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'tour_id' => Yii::t('app', 'Tour ID'),
            'tour_name' => Yii::t('app', 'Tour Name'),
            'description' => Yii::t('app', 'Description'),
            'start_date' => Yii::t('app', 'Start Date'),
            'end_date' => Yii::t('app', 'End Date'),
            'booking_deadline' => Yii::t('app', 'Booking Deadline'),
            'duration_days' => Yii::t('app', 'Duration Days'),
            'duration_nights' => Yii::t('app', 'Duration Nights'),
            'starting_point' => Yii::t('app', 'Starting Point'),
            'destination' => Yii::t('app', 'Destination'),
            'single_price' => Yii::t('app', 'Single Price'),
            'couple_price' => Yii::t('app', 'Couple Price'),
            'total_seats' => Yii::t('app', 'Total Seats'),
            'available_seats' => Yii::t('app', 'Available Seats'),
            'status' => Yii::t('app', 'Status'),
            'is_deleted' => Yii::t('app', 'Is Deleted'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActivities()
    {
        return $this->hasMany(\common\models\Activities::class, ['activity_id' => 'activity_id'])->viaTable('tour_activities', ['tour_id' => 'tour_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBookings()
    {
        return $this->hasMany(\common\models\Bookings::class, ['tour_id' => 'tour_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomers()
    {
        return $this->hasMany(\common\models\Customers::class, ['customer_id' => 'customer_id'])->viaTable('tour_reviews', ['tour_id' => 'tour_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvents()
    {
        return $this->hasMany(\common\models\Events::class, ['tour_id' => 'tour_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGuides()
    {
        return $this->hasMany(\common\models\TourGuides::class, ['guide_id' => 'guide_id'])->viaTable('tour_guides_assignments', ['tour_id' => 'tour_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPackageInclusions()
    {
        return $this->hasMany(\common\models\PackageInclusions::class, ['tour_id' => 'tour_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTourActivities()
    {
        return $this->hasMany(\common\models\TourActivities::class, ['tour_id' => 'tour_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTourGuides()
    {
        return $this->hasMany(\common\models\TourGuides::class, ['tour_id' => 'tour_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTourGuidesAssignments()
    {
        return $this->hasMany(\common\models\TourGuidesAssignments::class, ['tour_id' => 'tour_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTourImages()
    {
        return $this->hasMany(\common\models\TourImages::class, ['tour_id' => 'tour_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTourReviews()
    {
        return $this->hasMany(\common\models\TourReviews::class, ['tour_id' => 'tour_id']);
    }

}
