<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "tour_images".
 *
 * @property integer $image_id
 * @property integer $tour_id
 * @property string $image_url
 * @property string $caption
 *
 * @property \common\models\Tour $tour
 */
abstract class TourImages extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tour_images';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['tour_id', 'image_url'], 'required'],
            [['tour_id'], 'integer'],
            [['image_url','caption'], 'string', 'max' => 255],
            [['tour_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Tour::class, 'targetAttribute' => ['tour_id' => 'tour_id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'image_id' => Yii::t('app', 'Image ID'),
            'tour_id' => Yii::t('app', 'Tour ID'),
            'image_url' => Yii::t('app', 'Image Url'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTour()
    {
        return $this->hasOne(\common\models\Tour::class, ['tour_id' => 'tour_id']);
    }

}
