<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "tour_guides_assignments".
 *
 * @property integer $tour_id
 * @property integer $guide_id
 * @property string $assignment_date
 *
 * @property \common\models\TourGuides $guide
 * @property \common\models\Tours $tour
 */
abstract class TourGuidesAssignments extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tour_guides_assignments';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['assignment_date'], 'default', 'value' => 'curdate()'],
            [['tour_id', 'guide_id'], 'required'],
            [['tour_id', 'guide_id'], 'integer'],
            [['assignment_date'], 'safe'],
            [['tour_id', 'guide_id'], 'unique', 'targetAttribute' => ['tour_id', 'guide_id']],
            [['guide_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\TourGuides::class, 'targetAttribute' => ['guide_id' => 'guide_id']],
            [['tour_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Tours::class, 'targetAttribute' => ['tour_id' => 'tour_id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'tour_id' => Yii::t('app', 'Tour ID'),
            'guide_id' => Yii::t('app', 'Guide ID'),
            'assignment_date' => Yii::t('app', 'Assignment Date'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGuide()
    {
        return $this->hasOne(\common\models\TourGuides::class, ['guide_id' => 'guide_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTour()
    {
        return $this->hasOne(\common\models\Tours::class, ['tour_id' => 'tour_id']);
    }

}
